#!/bin/bash
# Same 6 DSRL runs as sbatch_multitask_28-32_all.sh, but with --seed 1
# instead of --seed 0. Job names get an `_s1` suffix so they don't collide
# in slurm_logs or wandb with the seed-0 counterparts.
#
# Submit:  bash examples/scripts/sbatch_multitask_28-32_all_s1.sh
set -euo pipefail
mkdir -p /global/home/users/ehharrison/dsrl_pi0/slurm_logs
# Job 0: multi-task on tasks {28, 29, 30, 31, 32}
jobid0=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_multi28-32_utd20_s1 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_multi28-32_utd20_s1.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_multi28-32_utd20_s1.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero DSRL_MULTI_TASK_IDS=28,29,30,31,32 bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 1 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid0  (dsrl_multi28-32_utd20_s1)"
# Job 1: single-task baseline, task 28
jobid1=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t28_utd20_s1 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t28_utd20_s1.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t28_utd20_s1.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 1 28 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid1  (dsrl_t28_utd20_s1)"
# Job 2: single-task baseline, task 29
jobid2=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t29_utd20_s1 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t29_utd20_s1.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t29_utd20_s1.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 1 29 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid2  (dsrl_t29_utd20_s1)"
# Job 3: single-task baseline, task 30
jobid3=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t30_utd20_s1 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t30_utd20_s1.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t30_utd20_s1.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 1 30 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid3  (dsrl_t30_utd20_s1)"
# Job 4: single-task baseline, task 31
jobid4=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t31_utd20_s1 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t31_utd20_s1.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t31_utd20_s1.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 1 31 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid4  (dsrl_t31_utd20_s1)"
# Job 5: single-task baseline, task 32
jobid5=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t32_utd20_s1 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t32_utd20_s1.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t32_utd20_s1.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 1 32 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid5  (dsrl_t32_utd20_s1)"
# Job 6: multi-task on tasks {28, 29, 30, 31, 32}
jobid6=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_multi28-32_utd20_s0 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_multi28-32_utd20_s0.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_multi28-32_utd20_s0.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero DSRL_MULTI_TASK_IDS=28,29,30,31,32 bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 0 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid6  (dsrl_multi28-32_utd20_s0)"
# Job 7: single-task baseline, task 28
jobid7=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t28_utd20_s0 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t28_utd20_s0.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t28_utd20_s0.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 0 28 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid7  (dsrl_t28_utd20_s0)"
# Job 8: single-task baseline, task 29
jobid8=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t29_utd20_s0 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t29_utd20_s0.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t29_utd20_s0.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 0 29 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid8  (dsrl_t29_utd20_s0)"
# Job 9: single-task baseline, task 30
jobid9=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t30_utd20_s0 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t30_utd20_s0.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t30_utd20_s0.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 0 30 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid9  (dsrl_t30_utd20_s0)"
# Job 10: single-task baseline, task 31
jobid10=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t31_utd20_s0 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t31_utd20_s0.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t31_utd20_s0.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 0 31 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid10  (dsrl_t31_utd20_s0)"
# Job 11: single-task baseline, task 32
jobid11=$(sbatch -A co_rail -p savio4_gpu --gres=gpu:A5000:1 -N 1 -n 1 -c 4 --qos=rail_gpu4_high -t 72:00:00 --mem=60G -J dsrl_t32_utd20_s0 -o /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t32_utd20_s0.%j.out -e /global/home/users/ehharrison/dsrl_pi0/slurm_logs/dsrl_t32_utd20_s0.%j.err --requeue --parsable --wrap 'source /global/home/users/ehharrison/miniconda3/etc/profile.d/conda.sh && conda activate dsrl_pi0 && cd /global/home/users/ehharrison/dsrl_pi0 && DSRL_TRAIN_ENV=libero bash /global/home/users/ehharrison/dsrl_pi0/examples/scripts/run_ablation.sh 0 20 0 32 --wandb_project DSRL_pi0_Libero_MultiTask --max_online_trajs 5000') && echo "submitted $jobid11  (dsrl_t32_utd20_s0)"
